service: videoproject
frameworkVersion: "3"
configValidationMode: error

plugins:
  - serverless-bundle
  - serverless-offline

package:
  patterns:
    - "!terraform/**"

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  region: us-west-2
  iam:
    role: ${ssm:api_lambdaExecutionRole}
  httpApi:
    cors: true
    authorizers:
      cognitoJwtAuth:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: ${ssm:cognito_issuerUrl} # pulling value out of parameter store
        # would be nice to split a StringList param store var, but cant get it working
        # audience: { "Fn::Split": [",", "${ssm:/cognito/audience}"] }
        audience:
          - ${ssm:cognito_devlocal_clientId}
          - ${ssm:cognito_mobiledevlocal_clientId}

functions:
  #########
  # /user #
  #########

  user_post:
    handler: src/api/endpoints/user/post.handler
    events:
      - httpApi:
          path: /user
          method: post
          authorizer:
            name: cognitoJwtAuth

  user_post_video:
    handler: src/api/endpoints/user/post-videos.handler
    events:
      - httpApi:
          path: /user/videos
          method: post
          authorizer:
            name: cognitoJwtAuth

  #########
  # /auth #
  #########

  auth_token:
    handler: src/api/endpoints/auth/token.handler
    events:
      - httpApi:
          path: /auth/token
          method: post

  auth_refresh:
    handler: src/api/endpoints/auth/refresh.handler
    events:
      - httpApi:
          path: /auth/refresh
          method: post

  ##########
  # /video #
  ##########

  video_get_by_id:
    handler: src/api/endpoints/video/get-by-id.handler
    events:
      - httpApi:
          path: /video/{videoId}
          method: get
          authorizer:
            name: cognitoJwtAuth

  #########
  # /feed #
  #########

  feed_get_candidates:
    handler: src/api/endpoints/feed/get-candidates.handler
    events:
      - httpApi:
          path: /feed/candidate
          method: get
          authorizer:
            name: cognitoJwtAuth

  #########
  # /tag #
  #########

  tag_post:
    handler: src/api/endpoints/tag/post-tag.handler
    events:
      - httpApi:
          path: /tag
          method: post
          authorizer:
            name: cognitoJwtAuth

  tag_get_all:
    handler: src/api/endpoints/tag/get-tag.handler
    events:
      - httpApi:
          path: /tag
          method: get
          authorizer:
            name: cognitoJwtAuth
