service: videoproject
frameworkVersion: "3"
configValidationMode: error

plugins:
  - serverless-offline

package:
  patterns:
    - "!terraform/**"

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  region: us-west-2
  iam:
    role: ${ssm:/api/lambdaExecutionRole}
  httpApi:
    cors: true
    authorizers:
      cognitoJwtAuth:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: ${ssm:/cognito/issuerUrl} # pulling value out of parameter store
        # would be nice to split a StringList param store var, but cant get it working
        # audience: { "Fn::Split": [",", "${ssm:/cognito/audience}"] }
        audience:
          - ${ssm:/cognito/audience/devlocal}
  environment:
    APP_TEST_VAR: birdsarentreal

functions:
  hello:
    handler: src/api/handler.handler
    events:
      - httpApi:
          path: /hello
          method: get
          authorizer:
            name: cognitoJwtAuth

  usersTest:
    handler: src/api/testHandler.handler
    events:
      - httpApi:
          path: /users/{userId}
          method: get
          authorizer:
            name: cognitoJwtAuth

  createUser:
    handler: src/api/users/create.handler
    events:
      - httpApi:
          path: /users
          method: post
          authorizer:
            name: cognitoJwtAuth
            
  # getUserProfile
  # getUserSettings
  # updateUser
  # delteUser