service: videoproject
frameworkVersion: "3"
configValidationMode: error

plugins:
  - serverless-bundle
  - serverless-offline

package:
  patterns:
    - "!terraform/**"

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  region: us-west-2
  iam:
    role: ${ssm:/api/lambdaExecutionRole}
  httpApi:
    cors: true
    authorizers:
      cognitoJwtAuth:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: ${ssm:/cognito/issuerUrl} # pulling value out of parameter store
        # would be nice to split a StringList param store var, but cant get it working
        # audience: { "Fn::Split": [",", "${ssm:/cognito/audience}"] }
        audience:
          - ${ssm:/cognito/devlocal/clientId}
          - ${ssm:/cognito/mobiledevlocal/clientId}

functions:
  hello:
    handler: src/api/testHandler.handler
    events:
      - httpApi:
          path: /hello
          method: get
          authorizer:
            name: cognitoJwtAuth

  getUser:
    handler: src/api/users/get.handler
    events:
      - httpApi:
          path: /user/{userId}
          method: get
          authorizer:
            name: cognitoJwtAuth

  createUser:
    handler: src/api/users/create.handler
    events:
      - httpApi:
          path: /user
          method: post
          authorizer:
            name: cognitoJwtAuth

  updateUser:
    handler: src/api/users/update.handler
    events:
      - httpApi:
          path: /user
          method: patch
          authorizer:
            name: cognitoJwtAuth

  deleteUser:
    handler: src/api/users/delete.handler
    events:
      - httpApi:
          path: /user
          method: delete
          authorizer:
            name: cognitoJwtAuth

  auth_token:
    handler: src/api/auth/token.handler
    events:
      - httpApi:
          path: /auth/token
          method: post

  auth_refresh:
    handler: src/api/auth/refresh.handler
    events:
      - httpApi:
          path: /auth/refresh
          method: post

  user_post_video:
    handler: src/api/user/post-userId-videos.handler
    events:
      - httpApi:
          path: /user/{userId}/videos
          method: post
          authorizer:
            name: cognitoJwtAuth
